name: phsps_api_work
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  alert_system: ^0.0.4
  bloc: ^8.1.2
  bot_toast: ^4.0.4
  equatable: ^2.0.5
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  side_navigation: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
