// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDexkIvRhW3aXMqWCJnAQWSvfmeRNsfzjY',
    appId: '1:333922084852:web:3b2b78eee42bd0b72f3ba1',
    messagingSenderId: '333922084852',
    projectId: 'phsps-1',
    authDomain: 'phsps-1.firebaseapp.com',
    storageBucket: 'phsps-1.appspot.com',
    measurementId: 'G-0EE05LQZH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI2cRTu2vVAYqVeSoAQiAK89IJywuVY2w',
    appId: '1:333922084852:android:0de37594218d1a012f3ba1',
    messagingSenderId: '333922084852',
    projectId: 'phsps-1',
    storageBucket: 'phsps-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZSTzmfT6ufXajLUpH1iIzGT8Qc66X-Kw',
    appId: '1:333922084852:ios:0dbebb2dcfae11fe2f3ba1',
    messagingSenderId: '333922084852',
    projectId: 'phsps-1',
    storageBucket: 'phsps-1.appspot.com',
    iosClientId: '333922084852-q70uedqfmjd5rt3v95bhobq5o2t5ejvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.phspsApiWork',
  );
}
